export const DIAGNOSIS_CLASS_NAME_ZH_CN = {
	Tomato___Late_blight: "番茄晚疫病",
	Tomato___healthy: "健康番茄",
	Grape___healthy: "健康葡萄",
	"Orange___Haunglongbing_(Citrus_greening)": "橙黄龙病（柑橘黄化病）",
	Soybean___healthy: "健康大豆",
	Squash___Powdery_mildew: "南瓜白粉病",
	Potato___healthy: "健康土豆",
	"Corn_(maize)__Northern_Leaf_Blight": "玉米北方叶枯病",
	Tomato___Early_blight: "番茄早疫病",
	Tomato___Septoria_leaf_spot: "番茄斑点病（Septoria）",
	"Corn(maize)__Cercospora_leaf_spot Gray_leaf_spot": "玉米灰叶斑病",
	Strawberry___Leaf_scorch: "草莓叶焦病",
	Peach___healthy: "健康桃子",
	Apple___Apple_scab: "苹果疮痂病",
	Tomato___Tomato_Yellow_Leaf_Curl_Virus: "番茄黄叶卷曲病毒病",
	Tomato___Bacterial_spot: "番茄细菌性斑点病",
	Apple___Black_rot: "苹果黑腐病",
	Blueberry___healthy: "健康蓝莓",
	"Cherry(including_sour)__Powdery_mildew": "樱桃白粉病",
	Peach___Bacterial_spot: "桃子细菌性斑点病",
	Apple___Cedar_apple_rust: "苹果雪松锈病",
	Tomato___Target_Spot: "番茄靶斑病",
	"Pepper,bell___healthy": "健康甜椒",
	"Grape___Leaf_blight(Isariopsis_Leaf_Spot)": "葡萄叶斑病（Isariopsis叶斑）",
	Potato___Late_blight: "土豆晚疫病",
	Tomato___Tomato_mosaic_virus: "番茄花叶病毒病",
	Strawberry___healthy: "健康草莓",
	Apple___healthy: "健康苹果",
	Grape___Black_rot: "葡萄黑腐病",
	Potato___Early_blight: "土豆早疫病",
	"Cherry(including_sour)__healthy": "健康樱桃（包括酸樱桃）",
	"Corn(maize)_Common_rust": "玉米常见锈病",
	"Grape___Esca(Black_Measles)": "葡萄Esca病（黑斑病）",
	Raspberry___healthy: "健康覆盆子",
	Tomato___Leaf_Mold: "番茄叶霉病",
	Soybean___Rust: "大豆锈病",
	Soybean__Anthracnose: "大豆炭疽病",
	"Tomato___Spider_mites Two-spotted_spider_mite": "番茄蜘蛛螨（两点蜘蛛螨）",
	"Pepper,bell___Bacterial_spot": "甜椒细菌性斑点病",
	"Corn(maize)___healthy": "健康玉米",
	"Apple Scab Leaf": "苹果黑星病叶",
	"Apple leaf": "苹果叶",
	"Apple rust leaf": "苹果锈病叶",
	"Bell_pepper leaf spot": "甜椒叶斑",
	"Bell_pepper leaf": "甜椒叶",
	"Blueberry leaf": "蓝莓叶",
	"Cherry leaf": "樱桃叶",
	"Corn Gray leaf spot": "玉米灰斑病叶",
	"Corn leaf blight": "玉米叶枯病",
	"Corn rust leaf": "玉米锈病叶",
	"Peach leaf": "桃叶",
	"Potato leaf early blight": "马铃薯早疫病叶",
	"Potato leaf late blight": "马铃薯晚疫病叶",
	"Potato leaf": "马铃薯叶",
	"Raspberry leaf": "覆盆子叶",
	"Soyabean leaf": "大豆叶",
	"Soybean leaf": "黄豆叶",
	"Squash Powdery mildew leaf": "南瓜白粉病叶",
	"Strawberry leaf": "草莓叶",
	"Tomato Early blight leaf": "番茄早疫病叶",
	"Tomato Septoria leaf spot": "番茄斑点病叶",
	"Tomato leaf bacterial spot": "番茄细菌性斑点病叶",
	"Tomato leaf late blight": "番茄晚疫病叶",
	"Tomato leaf mosaic virus": "番茄花叶病毒叶",
	"Tomato leaf yellow virus": "番茄黄化病毒叶",
	"Tomato leaf": "番茄叶",
	"Tomato mold leaf": "番茄霉变叶",
	"Tomato two spotted spider mites leaf": "番茄双斑螨叶",
	"grape leaf black rot": "葡萄叶黑腐病",
	"grape leaf": "葡萄叶"
} as const;

export type DiagnosisClassNameZhCn = keyof typeof DIAGNOSIS_CLASS_NAME_ZH_CN;
